config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  get 'orders/clean'
  get 'orders/index'
  get 'about/show'
  get 'contact/show'




  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks'
 }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories do
  resources :products
  end
  resources :products, only: [] do
    resources :orders, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:show, :edit]

  resources :orders, only: :index do
  collection do
    get 'clean'
  end
end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
  root to: 'categories#index'
end

app/views/shared/_alert.html.erb
<% if alert.present? %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

app/views/shared/_chart.html.erb
<h2>Por día</h2>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = Order.group_by_day(:created_at).count %>
<%= column_chart my_chart %>

<h2>Por mes</h2>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = Order.group_by_month(:created_at).count %>
<%= column_chart my_chart %>

<h2>Por año</h2>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = Order.group_by_year(:created_at).count %>
<%= column_chart my_chart %>

app/views/shared/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
   <div class="row">
     <div class="col-12 col-md">
       <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
       <small class="d-block mb-3 text-muted">&copy; 2019</small>
     </div>
     <div class="col-6 col-md">
       <h5>Mapa del Sitio</h5>
       <ul class="list-unstyled text-small">
         <li><a class="text-muted" href="<%= categories_path %>">Inicio</a></li>
         <li><a class="text-muted" href="<%= about_show_path %>">Quienes Somos</a></li>
         <li><a class="text-muted" href="#">Productos</a></li>
         <li><a class="text-muted" href="<%= contact_show_path %>">Contacto</a></li>
        </ul>
     </div>
     <div class="col-6 col-md">
       <h5>Productos</h5>
       <ul class="list-unstyled text-small">
         <li><a class="text-muted" href="#">Aceitunas</a></li>
         <li><a class="text-muted" href="#">Encurtidos</a></li>
         <li><a class="text-muted" href="#">Salsas</a></li>
      
       </ul>
     </div>
     <div class="col-6 col-md">
       <h5>Encuentranos</h5>
       <ul class="list-unstyled text-small">
         <li><a class="text-muted" href="#">Facebook</a></li>
         <li><a class="text-muted" href="htpp://www.instagram.com/pumoi.cl">Instagram</a></li>
         <li><a class="text-muted" href="#">Contacto</a></li>
       </ul>
     </div>
   </div>
 </footer>

app/views/shared/_navbar.html.erb
  <%= render 'shared/alert' %>
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= categories_path %>">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= about_show_path %>">Quienes Somos</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Productos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <h7><a class="dropdown-item" href="#">Aceitunas</a></h7>
          <h7><a class="dropdown-item" href="#">Encurtidos</a></h7>
          <h7><a class="dropdown-item" href="#">Salsas</a></h7>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= contact_show_path %>">Contacto</a>
        </li>
      </ul>
    </div>
    <div class="mx-auto order-0">
      <img src="../../assets/images/logo.png" alt="">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= orders_index_path %>">Mi carro <span class="sr-only">(current)</span></a>
        </li>
        <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse',  new_user_registration_path, class: 'nav-link'%>
        </li>
        <% else %>
        <li class="nav-item">
          <a class="nav-link"><%= current_user.name %></a>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% end %>
        </li>

      </ul>
    </div>

  </nav>