config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  get 'orders/clean'
  get 'orders/index'
  get 'about/show'
  get 'contact/show'




  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks'
 }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories do
  resources :products
  end
  resources :products, only: [] do
    resources :orders, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:show, :edit]

  resources :orders, only: :index do
  collection do
    get 'clean'
  end
end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
  root to: 'categories#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :product, optional: true
  belongs_to :cellar, optional: true

  belongs_to :billing, optional: true


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create

    p = Product.find(params[:product_id])
    o = Order.find_or_create_by(user: current_user, product: p, payed: false, price: p.price)
    o.quantity ? o.quantity += 1 : o.quantity = 1
    if o.save
      redirect_to category_path(p.category), notice: "El producto ha sido agregado al carro."
    else
      redirect_to category_path(p.category), alert: "El producto NO ha sido agregado al carro"
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.where(payed: false)
    @total = @orders.pluck("price * quantity").sum()
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/clean.html.erb
<h1>Orders#clean</h1>
<p>Find me in app/views/orders/clean.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
  <% if @orders.count > 0 %>
    <table class="table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Valor</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td> <%= order.product.name %> </td>
          <td> <%= order.price %></td>
          <td> <%= order.quantity %> </td>
          <td> <%= order.price * order.quantity %></td>
        </tr>
      <% end %>
      <tr class="table-dark">
      <td></td>
      <td></td>
      <td><strong>Total de la compra:</strong></td>
      <td><strong><%= @total %></strong></td>
      </tr>
    </tbody>
  </table>
  <%= link_to 'Confirmar compra', pre_pay_billings_path, class: 'btn btn-success float-right' %>
  <%= link_to 'Limpiar carro', clean_orders_path, class: 'btn btn-outline-danger'  %>

  <% else %>
    <p>No tienes productos en tu carro de compra.</p>

  <% end %>

</div>