config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  get 'orders/clean'
  get 'orders/index'
  get 'about/show'
  get 'contact/show'




  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks'
 }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories do
  resources :products
  end
  resources :products, only: [] do
    resources :orders, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products, only: [:show, :edit]

  resources :orders, only: :index do
  collection do
    get 'clean'
  end
end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
  root to: 'categories#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :orders
  has_many :stocks
  has_many :users, through: :orders
  has_one_attached :image
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :brand, :format, :photo, :cellar_id, :category_id, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
 <%= form.label :image %>
 <%= form.file_field :image %>
</div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :format %>
    <%= form.text_field :format %>
  </div>



  <div class="field">
    <%= form.label :cellar_id %>
    <%= form.text_field :cellar_id %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">


<p id="notice"><%= notice %></p>
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>image</th>
      <th>Name</th>
      <th>Brand</th>
      <th>Format</th>
      <th>Photo</th>
      <th>Cellar</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.brand %></td>
        <td><%= product.format %></td>
        <td><%= product.price %></td>
        <td><%= image_tag product.image if product.image.attached? %></td>
        <td><%= product.cellar_id %></td>
        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% if @product.image.attached? %>
<p>
  <strong>Image:</strong>
  <br>
  <%= image_tag @product.image %>
</p>
<% end %>

<p>
  <strong>Nombre Producto:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Formato:</strong>
  <%= @product.format %>
</p>
<p>
  <strong>Precio: $</strong>
  <%= @product.price %>
</p>


<p>
  <strong>Categoria:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', category_path(@product.category) %>